version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rafaalvfe
      - MONGO_INITDB_ROOT_PASSWORD=mysecurepassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis
    hostname: redis

volumes:
  mongo-db:
  